version: 2.1

orbs:
  python: circleci/python@0.2.1

commands:
  save-cache-bin:
    description: Save Pip packages to cache (with bin).
    parameters:
      key:
        default: pip
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - save_cache:
        key: << parameters.key >>-{{ checksum "requirements.txt"  }}
        paths:
        - /home/circleci/.local/lib/
        - /home/circleci/.local/bin/

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          name: Coverage deps
          command: |
              pip install coverage coveralls pyyaml
      - save-cache-bin
      - run:
          command: |
              find ~/.local
              # WTF no coverage executable?!
              #mkdir -p ~/.local/bin
              #cp ~/desimeter/.circleci/coverage ~/.local/bin
              #export PATH=${PATH}:~/.local/bin
              coverage run setup.py test
          name: Tests
      - run:
          name: Coveralls
          command: |
              # first set up project in coveralls.io, then
              # set this env.var in the circleci build config,
              # https://circleci.com/gh/desihub/desimeter/edit#env-vars
              echo "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} bundle exec rspec spec" > .coveralls.yml
              coveralls

workflows:
  main:
    jobs:
      - build-and-test
